magento2_sever:
    build: .
    dockerfile: ./docker/Dockerfile
    container_name: magento2
    working_dir: /var/www/html
    ports: 
        - "81:81"
    volumes: 
        - .:/var/www/html
        - ./docker/nginx_log:/var/log/nginx
        - ./docker/congfig/default.conf:/etc/nginx/con.f/default.conf
    links: 
        - mysql
mysql:
    image: mysql:5.6
    container_name: magento2_mysql
    ports: 
        - "3308:3308"
    volumes: 
        - ./docker/mysql:/var/lib/mysql
    environment: 
        MYSQL_ROOT_PASSWORD: "05052000"
        MYSQL_DATABASE: "magento2"
        MYSQL_USER: "trinhthikim"
        MYSQL_PASSWORD: "05052000"

